version: '3'

services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./data/:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wp/:/var/www/html
      - ./picksell-pay/:/var/www/html/wp-content/plugins/picksell-pay

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    command: >
      /bin/sh -c '
      sleep 30;
      wp core install --path="/var/www/html" --url="localhost:8000" --title="Picksell WooCommerce" --admin_user=picksell --admin_password=picksell --admin_email=picksell@psd2.club --allow-root;
      wp plugin install woocommerce --version=5.0.0 --activate --allow-root;
      wp theme install storefront --activate --allow-root;
      wp plugin install wordpress-importer --activate --allow-root;
      wp import /var/www/html/wp-content/plugins/woocommerce/*/*.xml --authors=create --allow-root;
      '
    volumes:
      - ./wp/:/var/www/html