version: '3'

services:
  db:
    image: mariadb:latest
    ports:
      - ${DB_EXTERNAL_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - ${WP_EXTERNAL_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_EXTERNAL_PORT}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wp/:/var/www/html
      - ./picksell-pay/:/var/www/html/wp-content/plugins/picksell-pay

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    command: >
      /bin/sh -c '
      sleep 30;
      wp core install --path="/var/www/html" --url="${WP_URL}:${WP_EXTERNAL_PORT}" --title="Picksell WooCommerce" --admin_user=${WP_USER} --admin_password=${WP_PASSWORD} --admin_email=${WP_EMAIL} --allow-root;
      wp plugin install woocommerce --version=${WOOCOMMERCE_VERSION} --activate --allow-root;
      wp theme install storefront --activate --allow-root;
      wp plugin install wordpress-importer --activate --allow-root;
      wp import wp-content/plugins/woocommerce/*/*.xml --authors=create --allow-root;
      '
    volumes:
      - ./wp/:/var/www/html